Feature/signin signup
vc-jinal/NodeJS-Tasks pull request #3
Opened 2023-05-17 08:11 UTC by vc-jinal

SignUp and SignIn using JWT token

2023-05-18 04:26 UTC, karansoni-vc requested changes

2023-05-18 11:29 UTC, vc-mohit commented on signup-signin-jwt/index.js
> +        return res.status(202).json({ token });//acept for proessing but not completed
@vc-jinal: use spell checker.

2023-05-18 11:29 UTC, vc-mohit commented on signup-signin-jwt/index.js
>          return res.json({ error: "Coudln't login " })
check message

2023-05-19 05:59 UTC, vc-mohit commented on signup-signin-jwt/index.js
> +        req.user = decoded;
decoded is not defined

2023-05-19 11:22 UTC, vc-jinal commented on signup-signin-jwt/index.js
> +        return res.json({ error: "user already exist.." });
Added status code and message

2023-05-19 11:23 UTC, vc-jinal commented on signup-signin-jwt/index.js
> +        return res.json({ err: "registration failed" });
removed sync method and added status code

2023-05-19 11:24 UTC, vc-jinal commented on signup-signin-jwt/index.js
> +        return res.json({ error: "Invalid email or password" })
Add message

2023-05-19 11:24 UTC, vc-jinal commented on signup-signin-jwt/index.js
> +    jwt.verify(token, jwtSecretkey, (err, decoded) => {
removed callback

2023-05-19 11:24 UTC, vc-jinal commented on signup-signin-jwt/index.js
> +            return res.json({ error: "Invalid email" })
Add message

2023-05-19 11:26 UTC, vc-jinal commented on signup-signin-jwt/index.js
> +        req.user = decoded;
removed callback and defined decoded

2023-05-19 11:27 UTC, vc-jinal commented on signup-signin-jwt/index.js
> +        return res.status(200).json({ token });
Add message

2023-05-19 12:58 UTC, vc-mohit commented on signup-signin-jwt/index.js
> +if (!fs.existsSync(userFile)) {
this function is working?

2023-05-19 13:54 UTC, vc-mohit commented
I am closing the Pull Request because of the following reason:
1. Lots of Spelling mistakes
2. All responses should be in JSON format only. (Use Send method)
3. Code should be properly formatted.

2023-05-19 13:54 UTC, closed without merging